version: '3.9'

services:
  mongo:
    restart: always
    image: mongo:4
    volumes:
      - type: volume
        target: /data/db
      - type: bind
        source: ./data/mongo-init
        target: /docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: 'my-app'

  mongo-express:
    restart: always
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo
